import { Toaster } from "@/components/ui/sonner";
import { DialogRenderer } from "@/components/dialogs/dynamic-renderer";
import { DialogProvider } from "@/lib/hooks/useDialogManager";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "NPI | Toolbox",
  description: "Generated by create next app",
};

export default function ToolboxLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Toaster richColors />

      <DialogProvider>
        <main>{children}</main>
        <DialogRenderer />
      </DialogProvider>
    </div>
  );
}
