import localFont from "next/font/local";
import type { Metadata } from "next";

import Navigation from "@/components/navigation";

import "@/css/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { FingerprintLoader } from "@/components/fingerprint-loader";

const universalSans = localFont({
  src: [
    {
      path: "../../public/fonts/UniversalSans-Thin.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/UniversalSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/UniversalSans-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/UniversalSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/UniversalSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "NPI | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={universalSans.className}>
      {/* <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" />
      </head> */}
      <body>
        <FingerprintLoader />
        <div className="fixed top-4 left-4 z-50">
          <div className="bg-background/90 border-border text-muted-foreground rounded-md border px-3 py-1.5 text-sm backdrop-blur-sm">
            FX Server: {process.env.FX_SERVER || "Development"}
          </div>
        </div>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
